yatube/about/urls.py
# about/urls.py
from django.urls import path

from about.views import AuthorPage, TechPage

app_name = 'about'

urlpatterns = [
    path('author/', AuthorPage.as_view(), name='author'),
    path('tech/', TechPage.as_view(), name='tech')
]

yatube/posts/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from posts import views

app_name = 'posts'

urlpatterns = [
    path(
        'profile/<str:username>/follow/',
        views.FollowView.as_view(),
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.UnfollowView.as_view(),
        name='profile_unfollow'
    ),
    path(
        '',
        cache_page(20, key_prefix='index_page')(
            views.IndexView.as_view(
                template_name='posts/index.html')
        ),
        name='index'
    ),
    path(
        'group/<slug:slug>/',
        views.GroupPostView.as_view(
            template_name='posts/group_list.html'
        ),
        name='group_list'
    ),
    path(
        'profile/<str:username>/',
        views.ProfileView.as_view(
            template_name='posts/profile.html'
        ),
        name='profile'
    ),
    path(
        'posts/<int:post_id>/', views.PostDetailView.as_view(
            template_name='posts/post_detail.html'
        ),
        name='post_detail'
    ),
    path(
        'create/', views.PostCreateView.as_view(
            template_name='posts/create_post.html'
        ),
        name='post_create'),
    path(
        'posts/<int:post_id>/edit/', views.PostEditView.as_view(
            template_name='posts/create_post.html'
        ),
        name='post_edit'
    ),
    path(
        'posts/<int:post_id>/comment/', views.CommentView.as_view(
            template_name='posts/post_detail.html'
        ),
        name='add_comment'
    ),
    path(
        'follow/', views.FollowIndexView.as_view(
            template_name='posts/follow.html'
        ),
        name='follow_index'
    )
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [path('', include('posts.urls', namespace='posts')),
               path('auth/', include('users.urls')),
               path('group_list/', include('posts.urls', namespace='posts')),
               path('admin/', admin.site.urls),
               path('auth/', include('django.contrib.auth.urls')),
               path('about/', include('about.urls', namespace='about'))]

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.csrf_failure'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

from core.models import CreatedModel


class Group(models.Model):
    title = models.CharField(
        'Группа, к которой будет относиться пост',
        max_length=200,
        help_text='Группа'
    )
    slug = models.SlugField(
        'Слаг группы',
        unique=True,
        help_text='Слаг группы'
    )
    description = models.TextField(
        'Описание группы',
        help_text='Описание группы'
    )

    def __str__(self) -> str:
        return self.title

    def __len__(self):
        return Post.objects.filter(group__slug=self.slug).count()


User = get_user_model()


class Post(CreatedModel):
    text = models.TextField(
        'Текст поста',
        help_text='Текст поста'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор',
        help_text='Автор поста'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True,
        help_text='Изображение'
    )

    class Meta:
        ordering = ('-pub_date',)
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self) -> str:
        return self.text[:15]


class Comment(CreatedModel):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Связанный пост',
        help_text='Пост, к которому привязан комментарий'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор коммента',
        help_text='Автор комментария'
    )
    text = models.TextField(
        'Текст комментария',
        help_text='Текст комментария'
    )

    class Meta:
        ordering = ('-pub_date',)
        verbose_name = 'Коммент'
        verbose_name_plural = 'Комменты'

    def __str__(self):
        return self.text[:15]


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        null=True,
        related_name='follower',
        verbose_name='Подписчик',
        help_text='Подписчик'
    )
    author = models.ForeignKey(
        User,
        related_name='following',
        null=True,
        on_delete=models.CASCADE,
        verbose_name='Автор',
        help_text='Автор'
    )

    class Meta():
        constraints = (
            models.UniqueConstraint(
                fields=('user', 'author'),
                name='unique_following'),
        )
        verbose_name = 'Подписка'
        verbose_name_plural = 'Подписки'

    def __str__(self) -> str:
        return f'{self.user} подписан на {self.author}'

yatube/posts/forms.py
from django import forms

from posts.models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text', )

yatube/posts/views.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import (CreateView, DetailView, ListView,
                                  RedirectView, UpdateView)

from posts.forms import CommentForm, PostForm
from posts.models import Follow, Group, Post

User = get_user_model()


class DataListMixin:
    model = Post
    paginate_by = settings.PER_PAGE


class IndexView(DataListMixin, ListView):

    def get_queryset(self):
        return Post.objects.all()


class GroupPostView(DataListMixin, ListView):

    def get_object(self):
        return get_object_or_404(Group, slug=self.kwargs.get('slug'))

    def get_queryset(self):
        return self.get_object().posts.all()

    def get_context_data(self, **kwargs):
        context = super(GroupPostView, self).get_context_data(**kwargs)
        context['group'] = self.get_object()
        return context


class ProfileView(DataListMixin, ListView):

    def get_object(self):
        return get_object_or_404(User, username=self.kwargs.get('username'))

    def get_queryset(self):
        return self.get_object().posts.all()

    def get_context_data(self, **kwargs):
        context = super(ProfileView, self).get_context_data(**kwargs)
        context['author'] = self.get_object()
        authenticated = self.request.user.is_authenticated
        following = authenticated and Follow.objects.filter(
            user=self.request.user, author=self.get_object()
        ).exists()
        context['following'] = following
        return context


class PostDetailView(DetailView):

    def get_object(self):
        return get_object_or_404(Post, id=self.kwargs.get('post_id'))

    def get_success_url(self):
        post_id = self.kwargs.get('post_id')
        return reverse_lazy(
            'posts/post_detail',
            kwargs={'post_id': post_id}
        )

    def get_comments(self):
        return self.get_object().comments.all()

    def get_context_data(self, **kwargs):
        context = super(PostDetailView, self).get_context_data(**kwargs)
        context['post'] = self.get_object()
        context['form'] = CommentForm()
        context['comments'] = self.get_comments()
        return context


class PostCreateView(LoginRequiredMixin, CreateView):
    form_class = PostForm

    def form_valid(self, form):
        post = form.save(commit=False)
        post.author = self.request.user
        post.save()
        return super().form_valid(form)

    def get_success_url(self):
        username = self.request.user.get_username()
        return reverse_lazy(
            'posts:profile',
            kwargs={'username': username}
        )


class PostEditView(LoginRequiredMixin, UpdateView):
    form_class = PostForm

    def get_object(self):
        return get_object_or_404(Post, id=self.kwargs.get('post_id'))

    def get_context_data(self, **kwargs):
        context = super(PostEditView, self).get_context_data(**kwargs)
        context['post'] = self.get_object()
        context['is_edit'] = True
        return context

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

    def get_success_url(self) -> str:
        return reverse_lazy(
            'posts:post_detail',
            kwargs={'post_id': self.kwargs.get('post_id')}
        )


class CommentView(LoginRequiredMixin, CreateView):
    form_class = CommentForm

    def get_object(self):
        return get_object_or_404(Post, id=self.kwargs.get('post_id'))

    def get_context_data(self, **kwargs):
        context = super(CommentView, self).get_context_data(**kwargs)
        context['comments'] = self.get_object().comments.all()
        context['form'] = CommentForm()
        return context

    def form_valid(self, form):
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = self.request.user
            comment.post = self.get_object()
            comment.save()
            return super().form_valid(form)
        return self.form_class()

    def get_success_url(self):
        post_id = self.get_object().id
        return reverse_lazy(
            'posts:post_detail',
            kwargs={'post_id': post_id}
        )


class FollowView(LoginRequiredMixin, RedirectView):

    def get(self, *args, **kwargs):
        if self.kwargs.get('username') == self.request.user.username:
            return redirect(
                reverse_lazy(
                    'posts:profile',
                    kwargs={'username': self.kwargs.get('username')}
                )
            )
        obj, created = Follow.objects.get_or_create(
            author=User.objects.get(username=self.kwargs.get('username')),
            user=self.request.user
        )
        if created:
            return super(FollowView, self).get(*args, **kwargs)
        return redirect(
            reverse_lazy(
                'posts:profile',
                kwargs={'username': self.kwargs.get('username')}
            )
        )

    def get_redirect_url(self, *args, **kwargs):
        return reverse_lazy(
            'posts:profile_follow',
            kwargs={'username': self.kwargs.get('username')}
        )


class UnfollowView(LoginRequiredMixin, RedirectView):

    def get(self, *args, **kwargs):
        follower = Follow.objects.filter(
            author__username=self.kwargs.get('username'),
            user=self.request.user
        )
        if follower.exists():
            follower.delete()
            return redirect(
                reverse_lazy(
                    'posts:profile',
                    kwargs={'username': self.kwargs.get('username')}
                )
            )
        return super(UnfollowView, self).get(*args, **kwargs)

    def get_redirect_url(self, *args, **kwargs):
        return reverse_lazy(
            'posts:profile_unfollow',
            kwargs={'username': self.kwargs.get('username')}
        )


class FollowIndexView(LoginRequiredMixin, DataListMixin, ListView):

    def get_queryset(self):
        return Post.objects.filter(author__following__user=self.request.user)

yatube/templates/posts/create_post.html
{% extends "base.html" %}
{% block title %}
  {% if is_edit %}
    Редактирование записи
  {% else %}
    Создание записи
  {% endif %}
{% endblock title %}
{% block content %}
<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">       
          {% if is_edit %}
            Редактировать запись {{ post.id }}
          {% else %}
            Создание записи
          {% endif %}             
        </div>
        <div class="card-body">        
          <form method="post"
            action=
            {% if is_edit %}
              {% url 'posts:post_edit' post.id %}
            {% else %}
              {% url 'posts:post_create' %}
            {% endif %}
            enctype="multipart/form-data">
            {% csrf_token %}   
            {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}
                    <li><strong>{{ field.label }} - {{ error|escape }}</strong></li>
                {% endfor %}
              {% endfor %}
            {% endif %}
            <div class="form-group row my-3 p-3">
              <label title="{{ form.text.label }}" for="{{ form.text.id_for_group }}">
                Введите текст сообщения:               
                <span class="required text-danger" >*</span>                  
              </label>
              {{ form.text }}                               
            </div>            
            <div class="form-group row my-3 p-3">
              <label title="{{ form.group.label }}" for="{{ form.group.id_for_label }}">
                Выберите группу:              
              </label>
              {{ form.group }}
            </div>
            <div class="form-group row my-3 py-3">
              <label title="{{ form.image.label }}" for="{{ form.image.id_for_group }}">
                Добавьте изображение:            
              </label>
              {{ form.image }}
            </div>
            <div class="d-flex justify-content-end">
              <button type="submit" class="btn btn-primary">
                Сохранить
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

yatube/templates/posts/follow.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}Лента подписок{% endblock title %}
{% block content %}
{% include 'posts/includes/switcher.html' %}
{% for post in page_obj %}
  {% include 'posts/includes/post_list.html' %}
{% endfor %}
  <div class="container">
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock content %}

yatube/templates/posts/group_list.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}Сообщения группы {{ group.title }}{% endblock title %}
{% block content %}
  <div class="container">
    <h1>Группа: {{ group.title }}</h1>
  </div>
  <div class="container d-flex justify-content-between align-items-center">        
    <p>{{ group.description }}</p>
    <p>Всего записей: {{ group.posts.count }}</p>
  </div>
{% for post in page_obj %}
  {% include 'posts/includes/post_list.html' %}
{% endfor %}
  <div class="container">
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock content %}

yatube/templates/posts/index.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}Последние обновления на сайте{% endblock title %}
{% block content %}
{% include 'posts/includes/switcher.html' %}
{% for post in page_obj %}
  {% include 'posts/includes/post_list.html' %}
{% endfor %}
  <div class="container">
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock content %}

yatube/templates/posts/post_detail.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}{{ post }}{% endblock title %}
{% block content %}
  <div class="row">
    <aside class=" card col-12 col-md-3">
      <ul class="list-group list-group-flush">
        {% if post.group %}
        <li class="list-group-item">
          Группа: {{ post.group.title }}
          <a href="{% url 'posts:group_list' post.group.slug %}">
            <p>Все записи группы</p>
          </a>
        {% endif %}
        </li>
        <li class="list-group-item">
          Автор: <a href="{% url 'posts:profile' post.author.get_username %}">{{ post.author.get_full_name }}</a>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора: <span>{{ post.author.posts.count }}</span>
        </li>
        <li class="list-group-item">
          <a href="{% url 'posts:profile' post.author %}">
            все посты пользователя
          </a>
        </li>
      </ul>
    </aside>
    <article class="col-8 col-md-6">
      {% include 'posts/includes/post_list.html' %}
      {% include 'posts/includes/comment_form.html' %}
    </article>
  </div> 
{% endblock content %}

yatube/templates/posts/profile.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}Профиль пользователя {{ author.get_full_name }}{% endblock title %}
{% block content %}
<div class="container">
  <h2>Пользователь {{ author.get_full_name }}</h2>
</div>
<div class="container">        
  <h4>Всего записей: {{ author.posts.count }}</h4>
  {% if author != request.user or request.user.is_anonymous %}
    {% if following %}
      <a
        class="btn btn-lg btn-light"
        href="{% url 'posts:profile_unfollow' author.username %}" role="button"
      >
        Отписаться
      </a>
    {% else %}
        <a
          class="btn btn-lg btn-primary"
          href="{% url 'posts:profile_follow' author.username %}" role="button"
        >
          Подписаться
        </a>
    {% endif %}
  {% endif %}
</div>
{% for post in page_obj %}
<div class="container">
  <div class="card row my-3 ">
    <div class="card-header">
      <h4 class="card-title">Сообщение {{ post.author.get_full_name }}</h4>
    </div>
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    <div class="card-block">
      <p class="card-text">{{post.text}}</p>
      <hr>
      <p><a href="{% url 'posts:post_detail' post.id %}">подробная информация </a></p>
    </div>
    <div class="card-footer d-flex justify-content-between align-items-center">
      <p class="card-text mb-2 text-muted"><b>Дата публикации:</b> {{ post.pub_date|date:"d E Y" }}</p>
      {% if post.author == request.user %}
        <a href="{% url 'posts:post_edit' post.id %}" class="btn btn-primary">Редактировать пост</a>
      {% endif %}
    </div>
  </div>
</div>
{% endfor %}
<div class="container">
  {% include 'posts/includes/paginator.html' %}
</div>
{% endblock content %}